# Generated by Django 5.2.3 on 2025-06-21 06:47

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                default="Johannesburg", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="country",
            field=django_countries.fields.CountryField(
                default="ZAR", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                default="44", max_length=100, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="street_address",
            field=models.CharField(
                default="Sue Avenue", max_length=150, verbose_name="Street Address"
            ),
        ),
    ]
